//
//  AutoMockable.swift
//  TestableSwiftApp
//
//  Created by Anders Persson on 2018-06-11.
//

import Foundation

// Mark objects that should be mocked with this protocol.
// The mocks will be generated by Sourcery.
protocol AutoMockable {
}

